module Unlight
end

# 一人プレイ時デュエル時にEntarantを操作するAIクラス
class Unlight::AI < Unlight::BaseEvent
end

# 条件と威力
module Unlight::AI::FeatChecker
end

Unlight::AI::FeatChecker::GREATER: untyped

Unlight::AI::FeatChecker::EQUAL: untyped

Unlight::AI::FeatChecker::SMALLER: untyped

Unlight::AI::FeatChecker::SHORT: untyped

Unlight::AI::FeatChecker::MIDDLE: untyped

Unlight::AI::FeatChecker::LONG: untyped

Unlight::AI::FeatChecker::MOVE: untyped

Unlight::AI::FeatChecker::ATK: untyped

Unlight::AI::FeatChecker::DEF: untyped

Unlight::AI::FeatChecker::FEAT_CONDITION: untyped
