module Unlight
end

Unlight::POINT_CHECK_MOVE: untyped

Unlight::POINT_CHECK_BATTLE: untyped

# 参加者クラス
class Unlight::Entrant < Unlight::BaseEvent
end

Unlight::Entrant::DEFAULT_CARD_NUM: untyped

Unlight::Entrant::DISTANCE_MAX: untyped

Unlight::Entrant::POINT_CHECK_MOVE: untyped

Unlight::Entrant::POINT_CHECK_BATTLE: untyped

Unlight::Entrant::EVENT_CARD_DRAW_NUM: untyped

Unlight::Entrant::DIRECTION_PEND: untyped

Unlight::Entrant::DIRECTION_FORWARD: untyped

Unlight::Entrant::DIRECTION_STAY: untyped

Unlight::Entrant::DIRECTION_BACKWARD: untyped

Unlight::Entrant::DIRECTION_CHARA_CHANGE: untyped

Unlight::Entrant::FIELD_STATUS: untyped
