module Unlight
end

# キャラクター本体のデータ
class Unlight::Achievement < Sequel::Model
end

Unlight::Achievement::CONDITION_SET: untyped

Unlight::Achievement::CHARA_CARD_CHECK_SHIFT_BIT: untyped

Unlight::Achievement::CHARA_CARD_CHECK_COMP_NUM: untyped

Unlight::Achievement::ITEM_SET_CALC_CHECK_SHIFT_BIT: untyped

Unlight::Achievement::ITEM_SET_CALC_CHECK_COMP_NUM: untyped
