module Unlight
end

# アバタークラス
class Unlight::Avatar < Sequel::Model
  include Avatars::Rookie

  include Avatars::Item

  include Avatars::Part

  include Avatars::Quest
end

Unlight::Unlight::Avatar::NAME_INPUT_SUCCESS: untyped

Unlight::Unlight::Avatar::NAME_ALREADY_USED: untyped

Unlight::Unlight::Avatar::NAME_CANT_USE: untyped

Unlight::Unlight::Avatar::RENAME_CHARACTORS: untyped
