module Unlight
end

# 合成条件
class Unlight::CombineCase < Sequel::Model
end

Unlight::Unlight::CombineCase::MOD_LIST: untyped

Unlight::Unlight::CombineCase::MOD_POINT_BASE_LIST: untyped

Unlight::Unlight::CombineCase::MOD_POINT_ADD_LIST: untyped

Unlight::Unlight::CombineCase::MOD_POINT_LIST: untyped
