inherit_from: .rubocop_todo.yml
inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-thread_safety
  - rubocop-sequel

AllCops:
  # The Ruby 2.7 changes may breaks UL server
  TargetRubyVersion: 2.6.8
  DisplayCopNames: true
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Exclude:
    - src/constants/common_constants.rb

Style/AsciiComments:
  Severity: info

# Use Rails-like style
RSpec/FilePath:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'src/**/*'
    - 'script/**/*'
    - 'bin/**/*'
