inherit_from: .rubocop_todo.yml

AllCops:
  # The Ruby 2.7 changes may breaks UL server
  TargetRubyVersion: 2.6.6
  DisplayCopNames: true

Layout/LineLength:
  Exclude:
    - src/constants/common_constants.rb
