language: ruby
rvm:
  - 2.6
cache: bundler
services:
  - mysql
  - memcached
env:
  global:
    - "DATABASE_URL=mysql2://root@localhost/unlight?encoding=utf8"
    - "MEMCACHED_HOST=localhost:11211"
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS unlight CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
  - gem install bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake db:migrate
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
