language: ruby
rvm:
  - 2.6
cache: bundler
services:
  - mysql
  - memcached
env:
  global:
    - "DATABASE_URL=mysql2://root@localhost/unlight?encoding=utf8"
    - "MEMCACHED_HOST=localhost:11211"
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS unlight CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
  - gem install bundler
script:
  - bundle exec rspec
