version: '3.4'

x-image: &image
  image: ${IMAGE}:latest
  restart: unless-stopped
  env_file:
    - .env
  environment:
    DATABASE_URL: mysql2://unlight:unlight@mysql/unlight_db?encoding=utf8mb4
    MEMCACHED_HOST: memcached:11211
  depends_on:
    - xmlsocket
    - memcached
    - mysql

services:
  memcached:
    image: memcached:alpine
    command: memcached -m 1024
    restart: unless-stopped
  mysql:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    environment:
      MYSQL_USER: unlight
      MYSQL_PASSWORD: unlight
      MYSQL_DATABASE: unlight_db
      MYSQL_ROOT_PASSWORD: unlight
    ports:
      - '3307:3306'
  # Flash Fallback
  xmlsocket:
    image: ${IMAGE}:latest
    restart: unless-stopped
    command: xmlsocket
    ports:
      - '11999:11999' # XMLSocket for Flash Policy
  # Game Server
  auth:
    <<: *image
    hostname: auth.lvh.me
    command: authentication -p 12001
    ports:
      - '12001:12001'
  lobby:
    <<: *image
    hostname: lobby.lvh.me
    command: lobby -p 12002
    ports:
      - '12002:12002'
  quest:
    <<: *image
    hostname: quest.lvh.me
    command: quest -p 12005
    ports:
      - '12005:12005'
  data:
    <<: *image
    hostname: data.lvh.me
    command: data_lobby -p 12032
    ports:
      - '12032:12032'
  game:
    <<: *image
    hostname: auth.lvh.me
    command: game -p 12008
    ports:
      - '12008:12008'
  match:
    <<: *image
    hostname: match.lvh.me
    command: matching -p 12018
    ports:
      - '12018:12018'
  chat:
    <<: *image
    hostname: chat.lvh.me
    command: chat -p 12012
    ports:
      - '12012:12012'
  watch:
    <<: *image
    hostname: watch.lvh.me
    command: watch -p 12080
    ports:
      - '12080:12080'
  global_chat:
    <<: *image
    hostname: global-chat.lvh.me
    command: global_chat -p 12020
    ports:
      - '12020:12020'
  raid:
    <<: *image
    hostname: raid.lvh.me
    command: raid -p 12050
    ports:
      - '12050:12050'
  raid_rank:
    <<: *image
    hostname: raid-rank.lvh.me
    command: raid_rank -p 12070
    ports:
      - '12070:12070'
  raid_chat:
    <<: *image
    hostname: raid-chat.lvh.me
    command: raid_chat -p 12090
    ports:
      - '12090:12090'
  raid_data:
    <<: *image
    hostname: raid-data.lvh.me
    command: raid_data -p 12100
    ports:
      - '12100:12100'
