version: '3.4'

x-image: &image
  image: ${IMAGE}:latest
  restart: unless-stopped
  env_file:
    - .env
  environment:
    DATABASE_URL: mysql2://unlight:unlight@mysql/unlight_db?encoding=utf8mb4
    MEMCACHED_HOST: memcached:11211
  depends_on:
    - memcached
    - mysql

services:
  memcached:
    image: memcached:alpine
    command: memcached -m 1024
  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_USER: unlight
      MYSQL_PASSWORD: unlight
      MYSQL_DATABASE: unlight_db
      MYSQL_ROOT_PASSWORD: unlight
    ports:
      - '3307:3306'
  xmlsocket:
    <<: *image
    command: xmlsocket
    ports:
      - '11999:11999' # XMLSocket for Flash Policy
  auth:
    <<: *image
    hostname: auth.lvh.me
    command: authentication -p 12001
    ports:
      - '12001:12001'
  lobby:
    <<: *image
    hostname: lobby.lvh.me
    command: lobby -p 12002
    ports:
      - '12002:12002'
  data:
    <<: *image
    hostname: data.lvh.me
    command: data_lobby -p 12032
    ports:
      - '12032:12032'
  game:
    <<: *image
    hostname: auth.lvh.me
    command: game -p 12008
    ports:
      - '12008:12008'
  # TODO: Add servers
