version: '3.4'

x-database: &database-environment
  MYSQL_USER: unlight
  MYSQL_PASSWORD: unlight
  MYSQL_DATABASE: unlight_db
  MYSQL_ROOT_PASSWORD: unlight

x-image: &image
  image: ${IMAGE}:latest
  restart: unless-stopped
  env_file:
    - .env
  environment:
    <<: *database-environment
    DB_HOST: mysql
    DB_ADAPTER: mysql
  depends_on:
    - memcached
    - mysql

services:
  memcached:
    image: memcached:alpine
    command: memcached -m 1024
  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      <<: *database-environment
    ports:
      - '3307:3306'
  auth:
    <<: *image
    hostname: auth.lvh.me
    command: authentication -p 12001
    ports:
      - '12001:12001'
  # TODO: Add servers
