ARG UNLIGHT_HOME=/opt/unlight
ARG RUBY_VERSION=3.2.2

# Pre-compile Gems
FROM ruby:${RUBY_VERSION}

# Setup Application
ARG UNLIGHT_HOME
ENV UNLIGHT_HOME=${UNLIGHT_HOME}
ENV RUBY_INLINE_DIR=${UNLIGHT_HOME}/lib/ruby_inline
ENV DAWN_LOG_TO_STDOUT=true
ENV PATH $UNLIGHT_HOME/bin:$PATH

RUN mkdir -p $UNLIGHT_HOME
WORKDIR $UNLIGHT_HOME

COPY Gemfile* $UNLIGHT_HOME/
SHELL ["/bin/bash", "-eo", "pipefail", "-c"]
RUN bundle install -j "$(getconf _NPROCESSORS_ONLN)"
