version: '3.4'

x-image: &image
  image: ${IMAGE}:latest
  restart: unless-stopped
  env_file:
    - .env
  depends_on:
    - memcached
    - mysql

services:
  memcached:
    image: memcached:alpine
    command: memcached -m 1024
  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file:
      - .env
    ports:
      - '3307:3306'
  auth:
    <<: *image
    hostname: auth.lvh.me
    command: authentication -p 12001
    ports:
      - '12001:12001'
  # TODO: Add servers
