version: '3.4'

x-image: &image
  image: ruby:${RUBY_VERSION:-3.2}
  volumes:
    - ${PWD}:/opt/unlight:cached
    - bundler_data:/usr/local/bundle
    - history:/usr/local/hist
    # for better DX
    - ./.irbrc:/root/.irbrc:ro
  working_dir: ${WORK_DIR:-/opt/unlight}
  environment:
    DATABASE_URL: mysql2://root:unlight@mysql/unlight_${ABYSS_ENV:-development}?encoding=utf8mb4
    MEMCACHED_HOST: memcached:11211
    # Unlight
    RUBY_INLINE_DIR: /opt/unlight/lib/ruby_inline
    # Development
    HISTFILE: /usr/local/hist/.bash_history
    LANG: C.UTF-8
    PROMPT_DIRTRIM: 2
    PS1: '[\W]\! '
  tmpfs:
    - /tmp
  depends_on:
    - memcached
    - mysql

services:
  memcached:
    image: memcached:alpine
    ports:
      - 11211
  mysql:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: unlight
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306

  # API Server
  api:
    <<: *image
    command: bin/abyss api
    ports:
      - 3000:3000

  # Game Server
  auth:
    <<: *image
    command: bin/abyss server auth -p 12001
    ports:
      - 12001
  lobby:
    <<: *image
    command: bin/abyss server lobby -p 12002
    ports:
      - 12002
  quest:
    <<: *image
    command: bin/abyss server quest -p 12005
    ports:
      - 12005
  data:
    <<: *image
    command: bin/abyss server data_lobby -p 12032
    ports:
      - 12032
  # Matching Related - Begin
  game:
    <<: *image
    command: bin/abyss server game -p 12008
    ports:
      - 12008
  match:
    <<: *image
    command: bin/abyss server matching -p 12018
    ports:
      - 12018
  chat:
    <<: *image
    command: bin/abyss server chat -p 12012
    ports:
      - 12012
  watch:
    <<: *image
    command: bin/abyss server watch -p 12080
    ports:
      - 12080
  # Matching Related - End
  global_chat:
    <<: *image
    command: bin/abyss server global_chat -p 12020
    ports:
      - 12020
  raid:
    <<: *image
    command: bin/abyss server raid -p 12050
    ports:
      - 12050
  raid_rank:
    <<: *image
    command: bin/abyss server raid_rank -p 12070
    ports:
      - 12070
  raid_chat:
    <<: *image
    command: bin/abyss server raid_chat -p 12090
    ports:
      - 12090
  raid_data:
    <<: *image
    command: bin/abyss server raid_data -p 12100
    ports:
      - 12100

volumes:
  mysql:
  bundler_data:
  history:
