default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  host: <%= ENV.fetch('DB_HOST', 'mysql') %>
  user: <%= ENV.fetch('DB_USER', 'unlight') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'unlight') %>

development:
  <<: *default
  database: unlight_development

test:
  <<: *default
  database: unlight_test
