module Unlight
end

Unlight::ACTION_EVENT_NO: untyped

class Unlight::DealedEvent < Unlight::EventRule
end

class Unlight::ThrowedEvent < Unlight::EventRule
end

class Unlight::DropedEvent < Unlight::EventRule
end

class Unlight::OccurChanceEvent < Unlight::EventRule
end

class Unlight::OccurHealEvent < Unlight::EventRule
end

class Unlight::OccurDamageEvent < Unlight::EventRule
end

class Unlight::OccurCureEvent < Unlight::EventRule
end

class Unlight::OccurCurseEvent < Unlight::EventRule
end

class Unlight::OccurChaliceEvent < Unlight::EventRule
end

class Unlight::OccurPoisonEvent < Unlight::EventRule
end

class Unlight::OccurDefeatEvent < Unlight::EventRule
end

class Unlight::OccurIdeaEvent < Unlight::EventRule
end

class Unlight::ChanceEvent < Unlight::EventRule
end

class Unlight::HealEvent < Unlight::EventRule
end

class Unlight::DamageEvent < Unlight::EventRule
end

class Unlight::CureEvent < Unlight::EventRule
end

class Unlight::CurseEvent < Unlight::EventRule
end

class Unlight::ChaliceEvent < Unlight::EventRule
end

class Unlight::PoisonEvent < Unlight::EventRule
end
