module Unlight
end

Unlight::AI_WAIT_TIME: untyped

# ===========================
# 更新関数定義
# ===========================
class Unlight::OneToOneAi < Unlight::EventRule
end

class Unlight::WaitingAction < Unlight::EventRule
end

class Unlight::ChoiceMoveCardAction < Unlight::EventRule
end

class Unlight::ChoiceAttackCardAction < Unlight::EventRule
end

class Unlight::ChoiceDeffenceCardAction < Unlight::EventRule
end

class Unlight::ChoiceCharaCardAction < Unlight::EventRule
end

class Unlight::DropChanceCardAction < Unlight::EventRule
end

class Unlight::DropMoveCardAction < Unlight::EventRule
end

class Unlight::DropAttackCardAction < Unlight::EventRule
end

class Unlight::DropDeffenceCardAction < Unlight::EventRule
end

class Unlight::SetCharaCardAction < Unlight::EventRule
end

class Unlight::DoneInitAction < Unlight::EventRule
end

class Unlight::DoneAttackAction < Unlight::EventRule
end

class Unlight::DoneDeffenceAction < Unlight::EventRule
end

class Unlight::MoveFeatHandSetAction < Unlight::EventRule
end

class Unlight::AttackFeatHandSetAction < Unlight::EventRule
end

class Unlight::DeffenceFeatHandSetAction < Unlight::EventRule
end

class Unlight::ResetThinkNumAction < Unlight::EventRule
end

# ===========================
# 判定定義
# ===========================
class Unlight::DecisionFeatAction < Unlight::EventRule
end

class Unlight::DecisionDistAction < Unlight::EventRule
end

class Unlight::DecisionAttackAction < Unlight::EventRule
end

class Unlight::DecisionDeffenceAction < Unlight::EventRule
end

class Unlight::DecisionCharaChangeAction < Unlight::EventRule
end

class Unlight::FinishGameEvent < Unlight::EventRule
end
