# イベント定義
# dsc:
#   説明文
#     "説明"
# context:*
#   実行可能な文脈
#     ["obj", :event], ...
# guard:*
#   実行条件 （登録した条件の一つでも合致すれば実行）。指定なければ必ず実行。
#   ["reciver",:method],...
# goal:*
#   終了条件 （登録した条件の一つでも成功すれば成功）。指定なければ必ず終了。Hookの場合は逆に終了しない。
#   ["reciver",:method],...
# type:
#   関数はいつ実行されるのか
#   直ちに実行           type=>:instant < default
#   なにかの前に行われる type=>:before, :obj=>"reciver", :hook=>:method ,:priority =>0
#   なにかの後に行われ   type=>:after, :obj=>"reciver", :hook=>:method,:priority =>0
#   なにかを置き換える   type=>:proxy, :obj=>"reciver", :hook=>:method
#   (priorityは値の低い順に実行される。使用可能なのは整数のみ)
# duration:
#   終了しない場合どれくらい続くか？(Hook系のイベントには使用できない)
#   終わらない       :none <default
#   複数回           type=>:times, value=>x
#   秒               type=>:sec, value=>x
# event:
#   イベントを発行するか？
#   実行前     :start     (add_start_listener_xxx(method:yyyy), 返値:target)
#   実行後     :finish    (add_finish_listener_xxx(method:yyyy),返値:taeget,ret)
#   発行しない :< default
# func:
#   実行関数（hookする関数）
# act:
#   追加実行されるイベント
module Unlight
end

class Unlight::UseEnergyEvent < Unlight::EventRule
end

class Unlight::UseFreeDuelCountEvent < Unlight::EventRule
end

class Unlight::UpdateEnergyMaxEvent < Unlight::EventRule
end

class Unlight::UpdateRemainTimeEvent < Unlight::EventRule
end

class Unlight::GetExpEvent < Unlight::EventRule
end

class Unlight::LevelUpEvent < Unlight::EventRule
end

class Unlight::GetDeckExpEvent < Unlight::EventRule
end

class Unlight::DeckLevelUpEvent < Unlight::EventRule
end

class Unlight::UpdateGemsEvent < Unlight::EventRule
end

class Unlight::UpdateResultEvent < Unlight::EventRule
end

class Unlight::ItemGetEvent < Unlight::EventRule
end

class Unlight::ItemUseEvent < Unlight::EventRule
end

class Unlight::CoinUseEvent < Unlight::EventRule
end

class Unlight::PartGetEvent < Unlight::EventRule
end

class Unlight::SlotCardGetEvent < Unlight::EventRule
end

class Unlight::CharaCardGetEvent < Unlight::EventRule
end

class Unlight::QuestGetEvent < Unlight::EventRule
end

class Unlight::QuestStateUpdateEvent < Unlight::EventRule
end

class Unlight::QuestDeletedEvent < Unlight::EventRule
end

class Unlight::QuestProgressUpdateEvent < Unlight::EventRule
end

class Unlight::QuestDeckStateUpdateEvent < Unlight::EventRule
end

class Unlight::QuestFlagUpdateEvent < Unlight::EventRule
end

# By_K2
class Unlight::FloorCountUpdateEvent < Unlight::EventRule
end

class Unlight::QuestClearNumUpdateEvent < Unlight::EventRule
end

class Unlight::QuestFindAtUpdateEvent < Unlight::EventRule
end

class Unlight::EventQuestFlagUpdateEvent < Unlight::EventRule
end

class Unlight::EventQuestClearNumUpdateEvent < Unlight::EventRule
end

class Unlight::UpdateFriendMaxEvent < Unlight::EventRule
end

class Unlight::UpdatePartMaxEvent < Unlight::EventRule
end

class Unlight::GetQuestTreasureEvent < Unlight::EventRule
end

class Unlight::UpdateRecoveryIntervalEvent < Unlight::EventRule
end

class Unlight::UpdateQuestInventoryMaxEvent < Unlight::EventRule
end

class Unlight::UpdateExpPowEvent < Unlight::EventRule
end

class Unlight::UpdateGemPowEvent < Unlight::EventRule
end

class Unlight::UpdateQuestFindPowEvent < Unlight::EventRule
end

class Unlight::UpdateQuestPointEvent < Unlight::EventRule
end

class Unlight::VanishPartEvent < Unlight::EventRule
end

class Unlight::AchievementClearEvent < Unlight::EventRule
end

class Unlight::AddNewAchievementEvent < Unlight::EventRule
end

class Unlight::DeleteAchievementEvent < Unlight::EventRule
end

class Unlight::UpdateRankEvent < Unlight::EventRule
end

class Unlight::StartSaleEvent < Unlight::EventRule
end

class Unlight::DeckGetEvent < Unlight::EventRule
end

class Unlight::UpdateAchievementInfoEvent < Unlight::EventRule
end

class Unlight::DropAchievementEvent < Unlight::EventRule
end

class Unlight::SendProfoundInfoEvent < Unlight::EventRule
end

class Unlight::ResendProfoundInventoryEvent < Unlight::EventRule
end

class Unlight::ResendProfoundInventoryFinishEvent < Unlight::EventRule
end

class Unlight::ChangeFavoriteCharaIdEvent < Unlight::EventRule
end

class Unlight::UpdateCombineWeaponDataEvent < Unlight::EventRule
end
