module Unlight
end

class Unlight::DrawCardsEvent < Unlight::EventRule
end

class Unlight::DrawLowCardsEvent < Unlight::EventRule
end

class Unlight::DeckInitEvent < Unlight::EventRule
end

class Unlight::CreateChanceCardEvent < Unlight::EventRule
end

class Unlight::AppendJokerCardEvent < Unlight::EventRule
end
