# イベント定義
# dsc:
#   説明文
#     "説明"
# context:*
#   実行可能な文脈 （登録した条件の一つでも合致すれば実行）。指定なければ必ず実行。
#     obj, event, ...
# guard:*
#   実行条件 （登録した条件の一つでも合致すれば実行）。指定なければ必ず実行。
#   ["reciver",:method],...<-配列すべてがTrueの時のみTrue
# goal:*
#   終了条件 （登録した条件の一つでも成功すれば成功）。指定なければ必ず終了。Hookの場合は逆に終了しない。
#   ["reciver",:method],...<-配列すべてがTrueの時のみTrue
# type:
#   関数はいつ実行されるのか
#   直ちに実行           type=>:instant < default
#   なにかの前に行われる type=>:before, :obj=>"reciver", :hook=>:method ,:priority =>0
#   なにかの後に行われ   type=>:after, :obj=>"reciver", :hook=>:method,:priority =>0
#   なにかを置き換える   type=>:proxy, :obj=>"reciver", :hook=>:method
#   (priorityは値の低い順に実行される。使用可能なのは整数のみ)
# duration:
#   終了しない場合どれくらい続くか？(Hook系のイベントには使用できない)
#   終わらない       :none <default
#   複数回           type=>:times, value=>x
#   秒               type=>:sec, value=>x
# event: (Hook系のイベントには使用できない)
#   イベントを発行するか？
#   実行前     :start
#   実行後     :finish
#   発行しない :< default
# func:
#   実行関数（hookする関数）
# act:
#   追加実行されるイベント
module Unlight
end

class Unlight::SetDirectionAction < Unlight::EventRule
end

class Unlight::MoveCardAddAction < Unlight::EventRule
end

class Unlight::MoveCardRemoveAction < Unlight::EventRule
end

class Unlight::MoveCardRotateAction < Unlight::EventRule
end

class Unlight::AttackCardAddAction < Unlight::EventRule
end

class Unlight::AttackCardRemoveAction < Unlight::EventRule
end

class Unlight::AttackCardRotateAction < Unlight::EventRule
end

class Unlight::DeffenceCardAddAction < Unlight::EventRule
end

class Unlight::DeffenceCardRemoveAction < Unlight::EventRule
end

class Unlight::DeffenceCardRotateAction < Unlight::EventRule
end

class Unlight::CardRotateAction < Unlight::EventRule
end

class Unlight::EventCardRotateAction < Unlight::EventRule
end

class Unlight::AddTableAction < Unlight::EventRule
end

class Unlight::CharaChangeAction < Unlight::EventRule
end

class Unlight::InitDoneAction < Unlight::EventRule
end

class Unlight::MoveDoneAction < Unlight::EventRule
end

class Unlight::FinishMovePhaseAction < Unlight::EventRule
end

class Unlight::AttackDoneAction < Unlight::EventRule
end

class Unlight::DeffenceDoneAction < Unlight::EventRule
end

class Unlight::ChangeDoneAction < Unlight::EventRule
end

class Unlight::MoveAction < Unlight::EventRule
end

class Unlight::HideMoveAction < Unlight::EventRule
end

class Unlight::MoveCardAddSuccesEvent < Unlight::EventRule
end

class Unlight::BattleCardAddSuccesEvent < Unlight::EventRule
end

class Unlight::DamagedEvent < Unlight::EventRule
end

class Unlight::DetermineDamageEvent < Unlight::EventRule
end

class Unlight::ReviveEvent < Unlight::EventRule
end

class Unlight::ConstraintEvent < Unlight::EventRule
end

class Unlight::SetDamageLogEvent < Unlight::EventRule
end

class Unlight::PartyDamagedEvent < Unlight::EventRule
end

class Unlight::HealedEvent < Unlight::EventRule
end

class Unlight::HitPointChangedEvent < Unlight::EventRule
end

class Unlight::PartyHealedEvent < Unlight::EventRule
end

class Unlight::CuredEvent < Unlight::EventRule
end

class Unlight::SealedEvent < Unlight::EventRule
end

class Unlight::UsedCardsEvent < Unlight::EventRule
end

class Unlight::DealdEvent < Unlight::EventRule
end

class Unlight::UseActionCardEvent < Unlight::EventRule
end

class Unlight::DiscardEvent < Unlight::EventRule
end

class Unlight::DiscardTableEvent < Unlight::EventRule
end

class Unlight::PointUpdateEvent < Unlight::EventRule
end

class Unlight::PointRewriteEvent < Unlight::EventRule
end

class Unlight::SpecialDealedEvent < Unlight::EventRule
end

class Unlight::GraveDealedEvent < Unlight::EventRule
end

class Unlight::StealDealedEvent < Unlight::EventRule
end

class Unlight::SpecialEventCardDealedEvent < Unlight::EventRule
end

class Unlight::UpdateCardValueEvent < Unlight::EventRule
end

class Unlight::DiceRollEvent < Unlight::EventRule
end

class Unlight::UpdateWeaponEvent < Unlight::EventRule
end

class Unlight::BattlePhaseInitEvent < Unlight::EventRule
end

class Unlight::CardsMaxUpdateEvent < Unlight::EventRule
end

class Unlight::DuelBonusEvent < Unlight::EventRule
end

class Unlight::SpecialMessageEvent < Unlight::EventRule
end

class Unlight::DuelMessageEvent < Unlight::EventRule
end

class Unlight::AttributeRegistMessageEvent < Unlight::EventRule
end

class Unlight::SetTurnEvent < Unlight::EventRule
end

class Unlight::MovePhaseInitEvent < Unlight::EventRule
end

class Unlight::UpdateTrapEvent < Unlight::EventRule
end

class Unlight::TrapActionEvent < Unlight::EventRule
end

class Unlight::TrapUpdateEvent < Unlight::EventRule
end

class Unlight::DiceAttributeRegistEvent < Unlight::EventRule
end

class Unlight::SetFieldStatusEvent < Unlight::EventRule
end

class Unlight::SetInitiativeEvent < Unlight::EventRule
end

class Unlight::CardLockEvent < Unlight::EventRule
end

class Unlight::ClearCardLocksEvent < Unlight::EventRule
end

# ===========================
# 計算定義
# ===========================
class Unlight::BpCalcResolve < Unlight::EventRule
end

class Unlight::DpCalcResolve < Unlight::EventRule
end

class Unlight::MpCalcResolve < Unlight::EventRule
end

class Unlight::AlterMpEvent < Unlight::EventRule
end

class Unlight::MpEvaluationEvent < Unlight::EventRule
end
