module Unlight
end

Unlight::LIB_PATH: untyped

Unlight::BOT_SESSION: untyped

Unlight::BOT_SESSION_KEY: untyped

Unlight::SERVER_SB: untyped

Unlight::USE_DB_TYPE: untyped

Unlight::CARD_KIND_ON: untyped

Unlight::RMI_TYPE_ITEM: untyped

Unlight::RMI_TYPE_PARTS: untyped

Unlight::RMI_TYPE_EVENT_CARD: untyped

Unlight::RMI_TYPE_WEAPON_CARD: untyped

Unlight::RMI_TYPE_CHARA_CARD: untyped

Unlight::RMI_TYPE_DECK: untyped

Unlight::INIT_WAIT_TIME: untyped

Unlight::MOVE_WAIT_TIME: untyped

Unlight::BATTLE_WAIT_TIME: untyped

Unlight::BATTLE_TIMEOUT_TURN: untyped

Unlight::DEFAULT_DISTANCE: untyped
