module Unlight
end

Unlight::CPU_CHARA_CARDS: untyped

Unlight::CPU_WEAPON_CARDS: untyped

Unlight::CPU_EQUIP_CARDS: untyped

Unlight::CPU_EVENT_CARDS: untyped

Unlight::LAND_TREASURE: untyped

Unlight::MAP_REALITY: untyped

Unlight::MAP_REALITY_NUM: untyped
