module Unlight
end

Unlight::SERVER_USER_LIMIT: untyped

Unlight::THIS_SERVER: untyped

Unlight::OLD_LOT: untyped

Unlight::AVATAR_RECOVERY_SEC: untyped

Unlight::EXP_POW: untyped

Unlight::GEM_POW: untyped

Unlight::DUEL_BONUS_POW: untyped

Unlight::SALE_ADDITIONAL_TIME: untyped

Unlight::RANKING_COUNT_NUM: untyped

Unlight::QUEST_CAP: untyped

Unlight::EVENT_QUEST_CAP: untyped

Unlight::TUTORIAL_QUEST_CAP: untyped

Unlight::CHARA_VOTE_QUEST_CAP: untyped

Unlight::INVITE_MAX: untyped

Unlight::INVITE_PRESENTS: untyped

Unlight::INVITE_SUCC_LEVEL: untyped

Unlight::COMEBACK_EVENT: untyped

Unlight::COMEBACK_CHECK_PERIOD: untyped

Unlight::COMEBACK_SEND_PRESENTS: untyped

Unlight::COMEBACKED_PRESENTS: untyped

Unlight::ROOKIE_SALE_CHECK_ACHEVEMENT_ID: untyped

Unlight::ROOKIE_SALE_START_COND_AT_TIME: untyped

Unlight::ROOKIE_SALE_TIME: untyped

Unlight::ROOKIE_PRESENT_FLAG: untyped

Unlight::ROOKIE_PRESENTS: untyped

Unlight::CHARA_VOTE_EVENT: untyped

Unlight::CHARA_VOTE_RANKING_HIDE_TIME: untyped

Unlight::EVENT_LOGIN_BONUS_FLAG: untyped

Unlight::PLUS_EVENT_LOGIN_BONUS_FLAG: untyped

Unlight::EVENT_START_ITEM_SEND_CHECK_AT: untyped

Unlight::EVENT_START_ITEM_SEND_ID: untyped

Unlight::QUEST_EVENT_FLAG: untyped

Unlight::QUEST_EVENT_RANKING_NAME: untyped

Unlight::ONE_DAY_SALE_FLAG: untyped

Unlight::ONE_DAY_SALE_CHECK_AT: untyped

Unlight::PRF_DMG_EVENT_RANKING_NAME: untyped

Unlight::TOTAL_EVENT_RANKING_CHECK_PRF_TIME: untyped

Unlight::RECORD_OTHER_AVATAR_DUEL_CHECK_START: untyped

Unlight::HIGH_LOW_EVENT_REWARD_ENABLE: untyped

Unlight::RANDOM_SALE_FLAG: untyped

Unlight::PRF_AUTO_CREATE_EVENT_FLAG: untyped

Unlight::PRF_AUTO_PRF_WDAY: untyped

Unlight::PRF_AUTO_PRF_MAX: untyped

Unlight::PRF_AUTO_CREATE_INTERVAL: untyped

Unlight::PRF_AUTO_HELP_INTERVAL: untyped

Unlight::DUEL_IP_CHECK: untyped

Unlight::CHAT_START_DLG_1: untyped

Unlight::CHAT_START_DLG_2: untyped

Unlight::CHAT_START_DLG_3: untyped

Unlight::CHAT_START_DLG_4: untyped

Unlight::DUEL_PENALTY: untyped

Unlight::DUEL_ABORT_PENALTY_TIME: untyped

Unlight::DUEL_ABORT_CNT_REC_TIME: untyped

Unlight::DUEL_ABORT_CNT_NUM: untyped

Unlight::DUEL_CNT_ABORT_PENALTY_TIME: untyped

Unlight::DUEL_RADDER_LIST_CACHE_TIME: untyped

Unlight::DUEL_RADDER_MATCH_COST: untyped

Unlight::LOGIN_BONUS_OFFSET_TIME: untyped

Unlight::WEEK_DUEL_ACHIEVEMENT_CHECK_IDS: untyped

Unlight::WEEK_QUEST_ACHIEVEMENT_CHECK_IDS: untyped

Unlight::DAILY_ACHIEVEMENT_CHECK_IDS: untyped

Unlight::CONDITIONS_DAILY_ACHIEVEMENT_FLAG: untyped

Unlight::GET_WEAPON_ACHIEVEMENT_IDS: untyped

Unlight::DB_CONNECT_CHECK: untyped

Unlight::DUEL_NAME_PL: untyped

Unlight::DUEL_NAME_FOE: untyped

Unlight::DUEL_NAME_WATCH: untyped

Unlight::ACTV_START_TITLE: untyped

Unlight::ACTV_START_BODY: untyped

Unlight::TAG_COLLECT_EVENT_ON: untyped

Unlight::TAG_INIT_CHECK_ST: untyped

Unlight::TAG_INIT_CHECK_ED: untyped

Unlight::XMAS_EVENT_ON: untyped

Unlight::SPECIAL_MESSAGE_SET: untyped

Unlight::ATTRIBUTE_REGIST_MESSAGE_SET: untyped

Unlight::LOGIN_BONUS_ITEM: untyped

Unlight::EVENT_LOGIN_BONUS: untyped

Unlight::EVENT_LEADERS201606: untyped

Unlight::EVENT_LEADERS201609: untyped
