module Unlight
end

Unlight::GENRE_ODDS: untyped

Unlight::GENRE_ODDS_QUEST: untyped

Unlight::START_END_TABLE: untyped

Unlight::WILD_ITEM_GET: untyped

Unlight::RESULT_1VS1_LOSE: untyped

Unlight::RESULT_1VS1_WIN: untyped

Unlight::RESULT_3VS3_LOSE: untyped

Unlight::RESULT_3VS3_WIN: untyped

Unlight::RESULT_CPU_LOSE: untyped

Unlight::RESULT_CPU_WIN: untyped

Unlight::LEVEL_CAP_LOSE: untyped

Unlight::LEVEL_CAP_WIN: untyped

Unlight::EVENT_REWARD_ITEM: untyped

Unlight::EVENT_REWARD_NUM_IDX: untyped

Unlight::EVENT_REWARD_CPU_NUM: untyped

Unlight::EVENT_REWARD_ITEM_STEPS: untyped

Unlight::EVENT_REWARD_ITEM_STEP_NUM: untyped

Unlight::EVENT_CHARA_IDS: untyped

Unlight::EVENT_CHARA_REWARD_ITEM_STEPS: untyped

Unlight::EVENT_CHARA_REWARD_ITEM_STEP_NUM: untyped
